/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package vista;
import dao.UsuarioDAO;
import modelo.Usuario;
import util.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author Derick Mota
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }
Usuario usuarioActual;

public MenuPrincipal(Usuario u) {
    initComponents();
    this.usuarioActual = u;
    cargarTabla();
    
    btnActivar.setEnabled(usuarioActual.rol.equals("ADMIN"));
    btnEliminar.setEnabled(usuarioActual.rol.equals("ADMIN"));
    if (!usuarioActual.rol.equals("ADMIN")) {  
        btnAgregar.setEnabled(false);  
        btnModificar.setEnabled(false);  
        btnInactivar.setEnabled(false);  
    }
}


public void cargarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("User");
        modelo.addColumn("Role");
        modelo.addColumn("Asset");

        for (Usuario u : UsuarioDAO.usuarios.values()) {
            modelo.addRow(new Object[]{
                u.username,
                u.rol,
                u.activo
            });
        }

        tablaUsuarios.setModel(modelo);
    }


    /**

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnCerrarSesion = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Add");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Edit");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnInactivar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInactivar.setText("Deactivate");
        btnInactivar.addActionListener(this::btnInactivarActionPerformed);

        btnReinicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReinicio.setText("Reset");
        btnReinicio.addActionListener(this::btnReinicioActionPerformed);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaUsuarios);

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrarSesion.setText("Log Out");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        btnActivar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActivar.setText("Activate");
        btnActivar.addActionListener(this::btnActivarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Delete");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel4.setText("Main Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInactivar)
                .addGap(12, 12, 12)
                .addComponent(btnReinicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActivar)
                .addGap(15, 15, 15)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    String user = JOptionPane.showInputDialog("Usuario:");
    String pass = JOptionPane.showInputDialog("Password:");

    if (UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "User already exists");
        return;
    }

    if (!Utilidades.validarPassword(pass)) {
        JOptionPane.showMessageDialog(this, "Invalid password");
        return;
    }

    UsuarioDAO.usuarios.put(user, new Usuario(user, pass, "USER"));
    UsuarioDAO.guardar();
    cargarTabla();
    JOptionPane.showMessageDialog(this, "User added");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
                                            

    String user = JOptionPane.showInputDialog("Enter username:");

    if (!UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "User does not exist");
        return;
    }

    Usuario u = UsuarioDAO.usuarios.get(user);

    // 🔴 SI NO ES ADMIN → pedir contraseña actual
    if (!usuarioActual.rol.equals("ADMIN")) {

        String actual = JOptionPane.showInputDialog("Enter current password:");

        String actualEncriptada = Utilidades.encriptar(actual);

        if (!u.password.equals(actualEncriptada)) {
            JOptionPane.showMessageDialog(this, "Current password incorrect");
            return;
        }
    }

    // 🔵 Nueva contraseña
    String nueva = JOptionPane.showInputDialog("New password:");
    String confirmar = JOptionPane.showInputDialog("Confirm Password:");

    if (!nueva.equals(confirmar)) {
        JOptionPane.showMessageDialog(this, "They don't match");
        return;
    }

    if (!Utilidades.validarPassword(nueva)) {
        JOptionPane.showMessageDialog(this, "Does not meet requirements");
        return;
    }

    // 🔐 Guardar encriptada
    u.password = Utilidades.encriptar(nueva);
    UsuarioDAO.guardar();

    JOptionPane.showMessageDialog(this, "Password updated");

    cargarTabla(); // opcional si quieres refrescar
    }//GEN-LAST:event_btnReinicioActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    String user = JOptionPane.showInputDialog("User to modify:");

    if (!UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "It doesn't exist");
        return;
    }

    String nuevaPass = JOptionPane.showInputDialog("New password:");

    if (!Utilidades.validarPassword(nuevaPass)) {
        JOptionPane.showMessageDialog(this, "Does not meet requirements");
        return;
    }

    UsuarioDAO.usuarios.get(user).password = nuevaPass;
    UsuarioDAO.guardar();
cargarTabla();
    JOptionPane.showMessageDialog(this, "Updated user");

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed

    String user = JOptionPane.showInputDialog("User: ");

    if (!UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "It doesn't exist");
        return;
    }

    UsuarioDAO.usuarios.get(user).activo = false;
    UsuarioDAO.guardar();
cargarTabla();
    JOptionPane.showMessageDialog(this, "User inactive");
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
                                           
    new Login().setVisible(true); 
    this.dispose(); 

    
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed

    String user = JOptionPane.showInputDialog("User to activate:");

    if (!UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "User does not exist");
        return;
    }

    Usuario u = UsuarioDAO.usuarios.get(user);

    if (u.activo) {
        JOptionPane.showMessageDialog(this, "The user is already active");
        return;
    }

    u.activo = true;
    UsuarioDAO.guardar();

    JOptionPane.showMessageDialog(this, "User successfully activated");

    cargarTabla();
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
 String user = JOptionPane.showInputDialog("User to delete:");

    if (user == null) return; // canceló

    if (!UsuarioDAO.usuarios.containsKey(user)) {
        JOptionPane.showMessageDialog(this, "User does not exist");
        return;
    }

    // 🔴 Evitar eliminarse a sí mismo
    if (user.equals(usuarioActual.username)) {
        JOptionPane.showMessageDialog(this, "You cannot delete your own user");
        return;
    }

    // 🔴 Confirmación
    int opcion = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete the user?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );

    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }

    UsuarioDAO.usuarios.remove(user);
    UsuarioDAO.guardar();

    JOptionPane.showMessageDialog(this, "User successfully deleted");

    cargarTabla(); // 🔥 actualizar tabla
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
